before_script:
  - apt-get update -qq && apt-get install -y -qq git zip nodejs nodejs-legacy npm curl
  - npm install -g jpm
  - git submodule sync --recursive
  - git submodule update --init --recursive
  
stages:
  - build

build_firefox:
  stage: build
  artifacts:
    paths:
      - smg-music-display.crx
      - build/updateManifest.json
  script:
    # fetch old update manifest
    - mkdir -p build
    - curl https://martijnbrekelmans.com/SMG/smg_web_plugin/updateManifest.json > build/oldUpdateManifest.json
    # the generateUpdateManifest script needs to be run from its folder, otherwise it will fail
    - cd scripts
    - node generateUpdateManifest.js smg@martijnbrekelmans.com https://martijnbrekelmans.com/SMG/smg_web_plugin/

deploy_extension:
  stage: build
  artifacts: 
    paths:
    - smg-music-display.crx
    - smg-music-display.zip
  script:
    # the crazy stuff is there to ignore the .git folder, be wary, it is /not/ regex!
    - zip smg-music-display.zip -r ./*[!.git]
    - cp smg-music-display.zip smg-music-display.crx