before_script:
  - apt-get update -qq && apt-get install -y -qq git zip
  - git submodule foreach git pull

stages:
  - build

crxify:
  stage: build
  artifacts: 
    paths:
    - smg-music-display.crx
  script:
    # the crazy stuff is there to ignore the .git folder, be wary, it is /not/ regex!
    - zip smg-music-display.zip -r ./*[!.git]
    - mv smg-music-display.zip smg-music-display.crx